apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 80           # external service port
      targetPort: 8081      # container port 
