apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 250Mi
  hostPath: 
    path: "/opt/sonar/data/"
    type: DirectoryOrCreate
