apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 250Mi
  hostPath: 
    path: "/opt/sonar/logs/"
    type: DirectoryOrCreate
