apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: ms-prod
spec:
  selector:
    app: spring-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30084 
  type: NodePort
