apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
      - name: jenkins
        image: jenkins:2.60.3-alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"   
            memory: "500Mi" 
          limits:
            cpu: "500m"      
            memory: "1Gi" 
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
