kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: jenkins-server
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["create", "delete", "get", "list", "watch"]
